name: 请求Python打包
description: 提交一个请求来打包你的Python项目
title: "[打包请求] 你的项目名称"
labels: ["packaging-request", "pyinstaller"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### 项目详情
  - type: input
    id: python-version
    attributes:
      label: Python版本
      description: 输入一个已知支持该程序的Python版本(默认, 3.6.5)
      placeholder: 例如，3.9
    validations:
      required: false
  - type: dropdown
    id: target-platform
    attributes:
      label: 目标平台
      multiple: true
      options:
        - Windows x64
        - Windows x86
        - Linux arm64
        - Linux x86_64
        - Linux armv7
        - Mac
        - Mac arm64
        - Mac x86_64
  - type: markdown
    attributes:
      value: |
        ### 所需文件

        请附上一个ZIP文件，包括以下内容：

        1. Python脚本（`*.py`）- 要打包的主程序。
        2. `requirements.txt` - 程序的依赖项（可选）。
        3. `pyinstaller.spec` - 自定义PyInstaller规范文件（可选）。
        4. `README.md` - GitHub发布说明。
  - type: textarea
    id: files
    attributes:
      label: 附加文件
      description: 请附上一个包含所需文件的ZIP文件链接。
      placeholder: 请提供ZIP文件的下载链接
      value: ""
    validations:
      required: true
