name: 自动打包Python项目

on:
  issues:
    types: [opened, edited]

jobs:
  validate-issue:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 GitHub CLI
        run: |
          sudo apt-get update && sudo apt-get install -y gh

      - name: 获取 Issue 信息
        id: extract-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_BODY=$(gh issue view 2 --json body -q .body | sed 's/\r//g')
          echo "body=$ISSUE_BODY" >> $GITHUB_ENV
          
          # 提取 Python 版本
          PYTHON_VERSION=$(echo "$ISSUE_BODY" | sed -n '/### Python版本/{n;p}' || echo "3.9")
          echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT

          echo "python-version=$PYTHON_VERSION"
        
          # 提取目标平台
          TARGET_PLATFORM=$(echo "$ISSUE_BODY" | sed -n '/### 目标平台/{n;p}' || echo "Linux x86_64")
          echo "target-platform=$TARGET_PLATFORM" >> $GITHUB_OUTPUT

          echo "target-platform=$TARGET_PLATFORM"
          
          # 提取 ZIP 文件链接
          FILES_LINK=$(echo "$ISSUE_BODY" | grep -oP 'https:\/\/github\.com\/[^\s]+\/files\/[^\s]+')
          if [ -z "$FILES_LINK" ]; then
            echo "未找到 ZIP 文件链接，任务终止"
            exit 1
          fi
          echo "files=$FILES_LINK" >> $GITHUB_OUTPUT



  setup-environment-and-build:
    needs: validate-issue
    strategy:
      matrix:
        target-platform: ${{ fromJson(needs.validate-issue.outputs.target-platform) }}
    runs-on: ${{ matrix.target-platform }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.validate-issue.outputs.python-version }}

      - name: 确认 Python 版本
        run: python --version

      - name: 下载 ZIP 文件
        run: |
          wget -O project.zip "${{ needs.validate-issue.outputs.files }}"

      - name: 解压 ZIP 文件
        run: |
          mkdir project
          unzip project.zip -d project

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f project/requirements.txt ]; then
            pip install -r project/requirements.txt
          fi

      - name: 使用 PyInstaller 打包
        run: |
          pip install pyinstaller
          if [ -f project/*.spec ]; then
            pyinstaller project/*.spec
          else
            pyinstaller --onefile project/*.py
          fi

      - name: 保存打包结果
        run: |
          mkdir -p ${{ github.workspace }}/dist/${{ matrix.target-platform }}
          mv dist/* ${{ github.workspace }}/dist/${{ matrix.target-platform }}

  release-result:
    needs: setup-environment-and-build
    runs-on: ubuntu-latest
    steps:
      - name: 上传 Release 结果
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v$(date +%Y%m%d%H%M%S)"
          gh release create "$TAG_NAME" ./dist/**/* \
            --title "打包结果: $TAG_NAME" \
            --notes "针对以下平台生成的构建： ${{ needs.validate-issue.outputs.target-platform }}"

      - name: 关闭 Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "打包完成！请在 [GitHub Releases](https://github.com/${{ github.repository }}/releases/tag/$TAG_NAME) 中查看结果。"
          gh issue edit ${{ github.event.issue.number }} --state closed
